(defun en-pl (word)
  (cdr (assoc word '((cat . "kot")
                     (field . "pole")
                     (sun . "slonce")
                     (forest . "las")
                     (light . "swiatlo")
                     (war . "wojna")
                     (sword . "miecz")
                     (politics . "polityka")
                     (law court . "sad")
                     (school . "szkola")
                     (country . "kraj")))))

(defun en-ger (word)
  (cdr (assoc word '((cat . "Katze")
                     (field . "Feld")
                     (sun . "Sonne")
                     (forest . "Wald")
                     (light . "Licht")
                     (war . "Krieg")
                     (sword . "Schwert")
                     (politics . "Politik")
                     (law_court . "Gericht")
                     (school . "Schule")
                     (country . "Land")))))

(defun en-lat (word)
  (cdr (assoc word '((cat . "felis")
                     (field . "ager")
                     (sun . "sol")
                     (forest . "silva")
                     (light . "lux")
                     (war . "bellum")
                     (sword . "gladius")
                     (politics . "politica")
                     (law court . "forum")
                     (school . "schola")
                     (country . "terra")))))

(defun words (word-list)
  (dolist (word word-list)
    (let ((en-word (car word))
          (de-word (cdr (assoc (car word) (en-ger))))
          (lat-word (cdr (assoc (car word) (en-lat))))
          (pl-word (cdr (assoc (car word) (en-pl)))))
      (format t "~a in Latin is ~a~%" en-word lat-word)
      (format t "~a in German is ~a~%" en-word (en-ger en-word))
      (format t "~a in Polish is ~a~%" en-word pl-word))))


(defun help ()
  (print "Welcome to the multilingual dictionary!")
  (print "To look up a word and its translation, use the following syntax:")
  (print "\t(<word> . <language>)")
  (print "where <word> is the English word you want to translate,")
  (print "and <language> is either 'pl', 'ger', or 'lat' for Polish, German, or Latin, respectively.")
  (print "Here are ten examples of how to use the dictionary:")
  (print "1. (en-pl 'cat)")
  (print "2. (en-ger 'field)")
  (print "3. (en-lat 'sun)")
  (print "Results:  1. 'kot'  2. 'Feld'  3. 'sol'")
  (print "List translation: (words '((field) (war) (school)))"))
